# redis 配置
mercury.redis.host: 127.0.0.1
mercury.redis.port: 13069
mercury.redis.password: fg#BQ%mk*vH#E7B6

# cloud 配置
mercury.cloud.host: 127.0.0.1
mercury.cloud.port: 8500
mercury.cloud.default-zone-metadata-name: test
mercury.cloud.tags: gateway,test

# 日志文件存放目录
mercury.logging.path: /home/ubuntu/logs/mercury-gateway
