# 数据库连接配置
# driver-class-name
#mercury.datasource.driver: com.mysql.cj.jdbc.Driver
mercury.datasource.url: jdbc:mysql://${mercury.datasource.host}/${mercury.datasource.database}?serverTimezone=Asia/Shanghai&characterEncoding=utf8&allowPublicKeyRetrieval=true
# 连接地址
mercury.datasource.host: 127.0.0.1:3306
# database
mercury.datasource.database: mercury
mercury.datasource.username: mercury
#mercury.datasource.password: lzy123456
#mercury.datasource.password: ENC(2lfJOJdW5yK/uNOedk/15ocP2n+Aq4seDkk8IqAsYMulGi3iyS0PNX1e+0nkc+2A)
mercury.datasource.password: '{cipher}AQAOy/ZJTQ+lFjqqQyAkWyQQHvzraeua+IIElQGjhEeyFGITv3UXOVlRwCj1Is9GoDbPmNbuzyfm9dBeDySCQwLlviCuT1lEvKAOe1mwzPNOg+CGzOcRSgpBOQQNm7wpms8/Watv0NlRBf89Nz/wYMCXRJ/gIqKK+kngg1dFN1JQBd5P9qNoTmWCIWiefkHUXMvLlXl39vfseH/ByAF6SL0Sptm1GPHV4vOqUuuQFgVJGMYrCYB+wY4QHUWUmM6UP3ZGc0dJnnYw4UET/t1wO+lFrxwqh9gx1deqKpFAm6w6HUCJ2AKaug7CM3gB2sN0Xai6zh3SZOp29Qf0SDo7L+drg1zVeExBU5LjY56DzHxX9+TsO6gt2IueBby464rYJe0='

# redis 配置
mercury.redis.host: 127.0.0.1
mercury.redis.port: 6379
#mercury.redis.password: ENC(tFdHXQm/VtIlzGCKm9xbjXPldAOofbp5Ep1m7wEOAP33S1EFxbMu4w3BPgmABU228ysRjvGAwWB9DJQ4UcUZtA==)
mercury.redis.password: '{cipher}AQBihj1hd6fGVkw3pbcJcyQjhrLJPbW5QDn32eiEkflnXB/rzy3hmbZAxyyP4vficQbuh+cmp5XDWtzll/WKtaU6DDnus1dpSelWCVemXvBRwZQyFYzR/GarD5zzWpf8jZJeMxBdBYaJnwg5BfT7Kw6Otdwj07PlfM3EXpr8e/9eOgYuDMjGkxxQ1n3nsgkT7IgCV80+tZCbqkpFRx1cx1cWtZkYODtc8dGaHpGLqUMZYYftqDip3EsFdjnWjxYFzNBSK8J+FmObUczoEPsAu2iKDLOWBOz8D4y28QybEMm0ZXxTCRvhVzW7bFK8NNuE4GdUatC6TCK6u5lIWeY5oAsju72L5m/way/twCheOP44qb53lX0Y5QKw1ab7mInNzm7vxVPX5KaEhS55AvwR/p1J'

# cloud 配置
mercury.cloud.host: 127.0.0.1
mercury.cloud.port: 8500
mercury.cloud.default-zone-metadata-name: dev
mercury.cloud.tags: base-api,dev

# mercury minio
minio.enable: true
minio.endpoint: http://127.0.0.1:9000
minio.accessKey: minio
minio.secretKey: minio123

minio.webUrl: http://xxx

# 上传文件大小限制
mercury.multipart.maxFileSize: 10MB

# 系统日志配置 - logback
# logback-spring.xml 位置
mercury.logging.config: classpath:logback-spring.xml
# 日志文件存放目录
mercury.logging.path: /data/logs/mercury-base-api

# mercury swagger
swagger.enable: true
swagger.server.url: http://localhost:9800/mercury-boot-api
swagger.apiInfo.title: Mercury Boot快速开发平台
swagger.apiInfo.description: 前后端分离架构SpringBoot 2.x，SpringCloud，SpringSession， NG-ZORRO&Angular，Hibernate&Querydsl。
swagger.apiInfo.license: Apache 2.0
swagger.apiInfo.licenseUrl: http://www.apache.org/licenses/LICENSE-2.0
swagger.apiInfo.version: 0.0.1-SNAPSHOT
swagger.apiInfo.contact.name: LiuZhengYu
swagger.apiInfo.contact.url: https://github.com/VinceLiuzy
swagger.apiInfo.contact.email: vince.liuzy@outlook.com

# 热部署
mercury.devtools.enabled: true

# sql 打印调试
spring:
  jpa:
    show-sql: true
