server:
  port: 9830

spring:
  application:
    name: mercury-cloud-config
  profiles:
    active: dev

  cloud:
    consul:
      host: ${mercury.cloud.host}
      port: ${mercury.cloud.port}
      discovery:
        # health-check-path: /monitor/health
        health-check-interval: 20s
        instance-id: ${spring.application.name}-${spring.cloud.client.ip-address}-${server.port}
        hostname: ${spring.cloud.client.ip-address}
        port: ${server.port}
        default-zone-metadata-name: ${mercury.cloud.default-zone-metadata-name:dev}
        tags: ${mercury.cloud.tags:dev}

    config:
      server:
        git:
          uri: ${mercury.git.url}
          # 搜索 ~/.ssh 下的SSH private key, ie: ~/.ssh/id_rsa
          ignore-local-ssh-settings: false
          strict-host-key-checking: false
          clone-on-start: true
          default-label: ${mercury.git.defaultLabel}
          search-paths: ${mercury.git.searchPaths}
          # private-key: ${mercury.git.privateKey}

  rabbitmq:
    host: 114.132.242.164
    port: 5672
    username: root
    password: qaz123!#
    publisher-confirm-type: correlated

  security:
    user:
      name: admin
      password: lzy109238


management:
  endpoint:
    health:
      enabled: true
      show-details: always
    shutdown:
      enabled: true
    refresh:
      enabled: true
    busrefresh:
      enabled: true

encrypt:
  key-store:
    location: classpath:server.jks
    password: 0acHXbvCFjXv%Kcv
    alias: mercuryBootKey
    secret: f6l^b%s9mrmfOEU1

logging:
  config: classpath:logback-spring.xml

