
# cloud 配置
mercury.cloud.host: 127.0.0.1
mercury.cloud.port: 8500
mercury.cloud.default-zone-metadata-name: prod
mercury.cloud.tags: config,prod

# 日志文件存放目录
mercury.logging.path: /data/logs/mercury-cloud-config

# git 仓库
mercury.git.url: git@github.com:VinceLiuzy/mercury-boot-public.git
mercury.git.defaultLabel: main
mercury.git.searchPaths: config

