
# cloud 配置
mercury.cloud.host: 127.0.0.1
mercury.cloud.port: 8500
mercury.cloud.tags: config,dev

# 日志文件存放目录
mercury.logging.path: /data/logs/mercury-cloud-config

# git 仓库
mercury.git.url: git@github.com:VinceLiuzy/mercury-boot-public.git
mercury.git.defaultLabel: main
mercury.git.searchPaths: config
mercury.git.privateKey: |
                          -----BEGIN RSA PRIVATE KEY-----
                          MIIJKAIBAAKCAgEAvwLeqCxKypLxC5FimNChbOQFjVanPGOdkFfKO5DfJoePbPao
                          T5bU+2zTk9HPmle3NLm6f0D4L8isDs9EnJps8N05VMgbC0Z4zyQ+kRhjhMfsbFsZ
                          85V+dDMsOYMgwOJxq+MDtmf64dcmpyG/e1+s6QtllXDccsjsWjtOLol3Adayc19v
                          o+FbJrpevdEn+FECuC5eqgjatYF39BSQpJW40fwhVTJ/ycJ5uVJk0l3rUpF14ZkR
                          K+FuwGjpL5pU1jCyjgol0/KhPM585smY+O1SLh1Z4xtXNGYwJ4Xdz0dqNTucJoTD
                          kmwdg2d1ejNgBkGqXg36K3c0f8wb16pWt6VF9k16sCt+ULo/qGvkmx+/ADrO0vhi
                          jIGWVVXbnOErBsKAS0mMDCivdQ69K2kbUwujrAd8Oh4tfrlRBoA75pB8o40zKWLD
                          5X5tvjWFVAPZxHT8iVmAC/oWO2qBnCwoV5QZywD6l4z15cVqVpBZ8CBgb7lyjTEN
                          Bbo2hbqInaXovrPOTjb89rmoOABFTGEaLyD5tgM4FhBhF88XJfVQt4cNSkAvHESj
                          JgPMbcCY2XWIXNbS9i2AXD9IXi3scO1XT9wZ0aQ2wiFthSYZBcecmfQfp8DoQuFd
                          omBQflrNo9iq3X/Z9Mj18G4ligS/YHdQfgqEW4m9z+xl+G8rVBC852DZdq8CAwEA
                          AQKCAgEAjyGCYTiXbsa/U3DFFke3vtX7Bxc4x/rJdgEi7JG5dbC9G+SU6NbYj/LT
                          dIAS9c/m296UzoiLsZrIu2w7OLJLEg5jyJEOGtva6TV6oNVKtZPuKJ/3iVyrXj1+
                          VTZaU88baLb68DNoftTvBOw4BSYDdrnwjBP/TRAcc9zez+Z4Q+ty2xtXl9DlsdaT
                          6d8R+XQS+prcmsN5x+rVTRQf8wSycr9g5uupcDGHbwQ7wptYHA4d7Ef74wrRJ+M1
                          YVNfYQUqt18JS5ITmnIMjA/izh1fqGicE59IMF6mlOct+AXGo08gyohP2KelUfMz
                          x7c5rFaGaGZG4U05DM6QyoG8624wRn2nV4w2zXnwy2GJbxsyzDUGEhm0E8dG2KZn
                          8EAjKaYivClO0LKP40u6+Uht2KpRofeky/sPIL5zNHKKhR/pgcTgBQdJuDYj7pxk
                          2Ttte043rKsNRh52Vi/WdYBZuEVkAUCUKK8xjodFpZCzUDM7cPte1bP+lRgLf3Mt
                          0g5thtcPiUYAUNkOz1xSXbpBsV8mbms0wB8EXC/AhBpw2+bXzHunJHbttRgAafiq
                          LktkL40n1VXKAOv/O11BczctjwpTMHMaulUuntKxStIaik2ThaGTZcuwM7b5GqVQ
                          ZephuAOtHdojcoMrE5iqTgDWf04adqaegBQsX8DMer19vXbAv2kCggEBAOhPUZWR
                          VjCuuzORk9is/fHlM4nlNNCRaUto5t2L7oAX8ryxPif3KESK8NW09Og/ckMcoq+c
                          RIzEFjdcvRumvkqwo3SOS07/3a/Gs9IN3wqzx/IB7t3pQtpBngSlqOx2yiF4YvUm
                          jIIUcPBWYPlw0UbcHN4oL22qLRhInE0pwqyRmgxdaqtILhunJYxkhdAfEVmElSri
                          DB7JwBeMiIt6WJATZCo8dmbURDuNbvvSy3o+6VMIXDhDF7HDXic/IBU9maNmpszE
                          7xp0Z5ecYueY84ZbdEpWrpb4AJfMwT/A7h0OTGwxT0+utF31a+BkXsGuQaqRqnsH
                          fI1/HfxNEHHR4uUCggEBANJ9aLDH2/hlYwpE9e+tOyyO5vLOvUdMaXuJ66uJe7RI
                          AOkrgryxniZCfN21gRGpMNSrjkdgTiWWHSSXFGzh8GHTJsh9fZ6NPTYRgJZZds8/
                          ZMsd1fyZSp+6mSkla5sj1jPXNfJPS58s5f5M1lzS1QxmdtCTRT856C1+1G+wrczv
                          JQSDj1Kbxra6598cw5GcEzmc12KCZtXmNvNRD2jmfqG9ABEXCb7gaZHzb9N6XYMt
                          g+b3rldkZ07cglToeMyz40Vx6FFakzvt8ezktFhumo4Ayry3ZW6QZsqiiSktZfd+
                          HkrW4awZxR9ucIkoX0EHU+QOXy1mqHoYtFNqoylxtgMCggEAbviE1leovnSZRBcE
                          cvqgDA8awYJV6lOr4rPnpGkVsua9s1lPgbPU7nkYdl2Mp+y23kwtgom5TSzWF/ga
                          9bx/Jhqe2iym2MPs1+ypNWwe4XPjzT0TJ7onjy7NFxczTFGqWLazPrv9Xp35HTWF
                          +WHk9l5rA8xaa55hEDqPP2T1c43R8polPFCshdUgYKIcMcDFfueQgf2dII/rTNR6
                          3XXCHIDG1k4vmQtI1NHI9E5LmMe4mUtjEhUqmmXi8gh7gOn+HEoK38IrHY4BdjDk
                          JhGwMrw5HtGtcLxjPCA5KAU3OXX9F6muYzfnPQLhVz1a7lYZVCtlLoPzAXx5jG4b
                          ruM96QKCAQBKqS0PN3Tw4JWGuPs7LokEvxNwIKDGv3XS2hL732I/iiK4kjRnVeEw
                          1PiRc6X6a7bkWI25B5HwhxSDPAuEq4emS01AZDLAoHyLxx2DNuyLioLoAQc79+ue
                          SIO3Moy+lLGP5dA+yJ2cMkLKNtr6RdZH9bhDN1mimZmfOZOEonijblgFB904ggS0
                          IAvK+drstR2km9tSF8r+KBBpseDzZn6YQ//YEAHm8JbBrEWID6lHtEdLD6OJYBW8
                          xT59e5ANm+kLYuHyqVv8L+RWELFfhKvRnrpKwgp6c0HislBQiMfYR6XbCek2MFXZ
                          VkUYgXd4C29YPzjHU9iCpmygAf0p4CmdAoIBAEJQ94rPipKsEJCypdPRB3naxiQK
                          ko4uxlhD1394jOLkF86ZyzSw589iQJI33UJepWjRBfRqnTJKF/X5XR4Qb9L9k3yu
                          e9iwf/Dhh5R/y2BP2a/NE7JS6NwJXBo5FfABk1rxY4vCUFdWoPCw8Gsd/jJ/XXHP
                          vhvdSSWsEPYYQz7Fvy+zKSephIa9W8wOt0PUFcpDyLQ5WOpEHLu0wPAoF97wL8V0
                          Bx+TDuh8opWIOnUvriDgqzC0hGyxn2y/dqVfdwke7Od/U+H8lMZUgcA4RnNatHnu
                          CD0pfFRiJm62pLjSjNTFlwbiBd5RBURftWZ40kglnPO2mEErkzGOj2cFhAE=
                          -----END RSA PRIVATE KEY-----