server:
  port: 9830

spring:
  application:
    name: mercury-cloud-config
  profiles:
    active: dev

  cloud:
    consul:
      host: ${mercury.cloud.host}
      port: ${mercury.cloud.port}
      discovery:
        # health-check-path: /monitor/health
        health-check-interval: 20s
        instance-id: ${spring.application.name}-${spring.cloud.client.ip-address}-${server.port}
        hostname: ${spring.cloud.client.ip-address}
        port: ${server.port}
        default-zone-metadata-name: ${mercury.cloud.default-zone-metadata-name:dev}
        tags: ${mercury.cloud.tags:dev}

    config:
      server:
        git:
          uri: ${mercury.git.url}
          # 搜索 ~/.ssh 下的SSH private key, ie: ~/.ssh/id_rsa
          ignore-local-ssh-settings: false
          strict-host-key-checking: false
          clone-on-start: true
          default-label: ${mercury.git.defaultLabel}
          search-paths: ${mercury.git.searchPaths}
          # private-key: ${mercury.git.privateKey}

  rabbitmq:
    host: 114.132.242.164
    port: 5672
    username: root
    password: qaz123!#
    publisher-confirm-type: correlated

  security:
    user:
      name: admin
      password: '{cipher}AQBGYmJrfWhfHEoJeki1F6tai5IePlLxRjwwMwqOgLOWLvW7vpDU6OvGMLwTxA48KwjjxOfPN52ol1uIKdm/LWt8vGyg3MaD1cv90mc8uLjK05715zp4EbD+hWY6ucpZkTfhLQXffi1J2ROIBjvCL0Nud/7UeOAyII8NlaCET9P3e+X08rGxWrsao1LA6x/AGvEWhYOnNg3JI0Ro0Vs9yY78pwI3+3UdW9VZH1EV2/gTAUzd9pve5InSCTM9MhUTk+y+b1ZB3H199hejuRnEK68Ytgvbjde20M1ZY6DXX+Fyv1c1aHB9BlA9mIh+bX9plqJ7SFgSw9HMece9eO1LZGJG7SR4yQepgKekyq/rpoki4FGzjnPsrZLwSbODSWJq0Io='

management:
  endpoint:
    health:
      enabled: true
      show-details: always
    shutdown:
      enabled: true
    refresh:
      enabled: true
    busrefresh:
      enabled: true

encrypt:
  key-store:
    location: classpath:server.jks
    password: 0acHXbvCFjXv%Kcv
    alias: mercuryBootKey
    secret: f6l^b%s9mrmfOEU1

logging:
  config: classpath:logback-spring.xml

